### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.datasets.synthia'

### ISSUE THREAD

**Issue by NiuYingchun** [antao97/LGM#1]
非常优秀的工作，更加感谢能发布代码。我预处理室内场景S3DIS是，提示“ModuleNotFoundError: No module named 'lib.datasets.synthia'”，请问是不是缺少了文件？谢谢。另外，关于SemanticKitti户外攻击的代码能不能也开源一下，谢谢您。

**Comment by antao97** [comment]
感谢肯定！

出错的原因是`indoor_scene/lib/datasets/__pycache__/__init__.py`文件中应该删去`import lib.datasets.synthia as synthia`，现在代码已经更新好了。关于SemanticKitti户外攻击的代码我会近期考虑整理一下。

**Comment by NiuYingchun** [comment]
谢谢回复，个人认为3D点云语义分割的攻击与防御工作相对较少，相信您的工作会是这个小方向一个开山之作，再次谢谢开源。
&nbsp;


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2022年11月6日(星期天) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antao97/LGM] ModuleNotFoundError: No module named &#39;lib.datasets.synthia&#39; (Issue #1)





 
感谢肯定！
 
出错的原因是indoor_scene/lib/datasets/__pycache__/__init__.py文件中应该删去import lib.datasets.synthia as synthia，现在代码已经更新好了。关于SemanticKitti户外攻击的代码我会近期考虑整理一下。

**Comment by antao97** [comment]
室外场景的代码已开源，欢迎使用
